// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv ./cloudflare-env.d.ts`

/// <reference types="@cloudflare/workers-types" />

// Type declaration for cloudflare:test module used by @cloudflare/vitest-pool-workers
declare module 'cloudflare:test' {
	export const env: CloudflareEnv
}

interface CloudflareEnv {
	KV: KVNamespace
	ENVIRONMENT: string
	BETTER_AUTH_SECRET: string
	BETTER_AUTH_URL: string
	NEXTJS_ENV: string
	R2: R2Bucket
	DB: D1Database
	WORKER_SELF_REFERENCE: Fetcher
	AI: Ai
	ASSETS: Fetcher
	// Durable Objects for CF Agents
	HARE_AGENT: DurableObjectNamespace
	MCP_AGENT: DurableObjectNamespace
	// Vectorize index (optional - not all deployments have this configured)
	VECTORIZE?: VectorizeIndex
}
