// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv ./cloudflare-env.d.ts`

/// <reference types="@cloudflare/workers-types" />

// Type declaration for cloudflare:test module used by @cloudflare/vitest-pool-workers
declare module 'cloudflare:test' {
	export const env: CloudflareEnv
}

interface CloudflareEnv {
	KV: KVNamespace
	ENVIRONMENT: 'development'
	BETTER_AUTH_SECRET: 'dev-secret-change-in-production-min-32-chars'
	BETTER_AUTH_URL: 'http://localhost:3000'
	NEXTJS_ENV: string
	R2: R2Bucket
	DB: D1Database
	WORKER_SELF_REFERENCE: Fetcher
	VECTORIZE: VectorizeIndex
	AI: Ai
	ASSETS: Fetcher
}
