#!/usr/bin/env node

/**
 * Environment Variable Shim Script for Monorepo
 * 
 * This script generates environment files for different apps in the monorepo
 * from a single root .env.local file. It handles:
 * - Next.js apps: transforms PUBLIC_ to NEXT_PUBLIC_
 * - Cloudflare Workers: generates .dev.vars (excludes PUBLIC_ vars)
 * 
 * Based on: https://github.com/timothymiller/t4-app/blob/master/.github/scripts/env.ts
 * 
 * Usage:
 *   node .github/scripts/env.ts
 *   # or with bun:
 *   bun run .github/scripts/env.ts
 * 
 * Automatically runs via postinstall hook (skipped in CI).
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

// Get directory name for ES modules
const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const isCI = process.env.CI === 'true'
if (isCI) {
  console.log('🏃 CI detected, skipping .env file generation')
  process.exit(0)
}

console.log('🐇 Generating environment files for monorepo...')

const autogeneratedComment =
  '# This file is autogenerated. To make changes, modify the root level .env.local file and run bun install\n\n'
const sourceFileName = '.env.local'

// Read the source .env.local file
const rootDir = join(__dirname, '..', '..')
const envFilePath = join(rootDir, sourceFileName)

if (!existsSync(envFilePath)) {
  console.log('⚠️  .env.local file does not exist at root level')
  console.log('💡 Create one from .env.example: cp .env.example .env.local')
  process.exit(0)
}

const envFileContent = readFileSync(envFilePath, 'utf8')

/**
 * Generate Next.js .env.local file
 * Transforms PUBLIC_ prefix to NEXT_PUBLIC_
 */
const nextOutputPath = join(rootDir, 'apps', 'web', '.env.local')
const nextFileContent = envFileContent
  .split('\n')
  .map((line) => {
    // Transform PUBLIC_ to NEXT_PUBLIC_ for Next.js
    if (line.startsWith('PUBLIC_')) {
      return line.replace(/^PUBLIC_/, 'NEXT_PUBLIC_')
    }
    return line
  })
  .join('\n')

writeFileSync(nextOutputPath, `${autogeneratedComment}${nextFileContent}`)
console.log('✅ Generated apps/web/.env.local')

/**
 * Generate Cloudflare .dev.vars file
 * Cloudflare Workers uses .dev.vars for local development instead of .env
 * PUBLIC_ variables are excluded as they're typically client-side only
 */
const wranglerOutputPath = join(rootDir, 'apps', 'web', '.dev.vars')
const wranglerFileContent = envFileContent
  .split('\n')
  .filter((line) => {
    // Skip empty lines and comments
    if (!line.trim() || line.trim().startsWith('#')) {
      return true
    }
    // Exclude PUBLIC_ prefixed variables (client-side only)
    if (line.startsWith('PUBLIC_') || line.startsWith('NEXT_PUBLIC_')) {
      return false
    }
    return true
  })
  .join('\n')

writeFileSync(wranglerOutputPath, `${autogeneratedComment}${wranglerFileContent}`)
console.log('✅ Generated apps/web/.dev.vars')

console.log('🎉 Environment files generated successfully!')
