#!/usr/bin/env bun
/**
 * Generate Fumadocs MDX source files
 * Creates stub .source files if they don't exist for TypeScript to resolve
 * The real files are generated by the Vite MDX plugin during dev/build
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const sourceDir = join(import.meta.dirname, '../.source')

// Stub content for TypeScript resolution before first build
const serverStub = `// Auto-generated stub - real file created by fumadocs-mdx Vite plugin
export const docs = {
  toFumadocsSource: () => ({ files: [] })
}
`

const browserStub = `// Auto-generated stub
export {}
`

if (!existsSync(sourceDir)) {
	mkdirSync(sourceDir, { recursive: true })
	writeFileSync(join(sourceDir, 'server.ts'), serverStub)
	writeFileSync(join(sourceDir, 'browser.ts'), browserStub)
	writeFileSync(join(sourceDir, 'dynamic.ts'), browserStub)
	console.log('✅ Created .source stubs for TypeScript')
} else {
	console.log('✅ .source directory already exists')
}
