/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardUsageIndexRouteImport } from './routes/_dashboard/dashboard/usage/index'
import { Route as DashboardDashboardToolsIndexRouteImport } from './routes/_dashboard/dashboard/tools/index'
import { Route as DashboardDashboardSettingsIndexRouteImport } from './routes/_dashboard/dashboard/settings/index'
import { Route as DashboardDashboardAnalyticsIndexRouteImport } from './routes/_dashboard/dashboard/analytics/index'
import { Route as DashboardDashboardAgentsIndexRouteImport } from './routes/_dashboard/dashboard/agents/index'
import { Route as DashboardDashboardToolsNewRouteImport } from './routes/_dashboard/dashboard/tools/new'
import { Route as DashboardDashboardSettingsTeamRouteImport } from './routes/_dashboard/dashboard/settings/team'
import { Route as DashboardDashboardSettingsBillingRouteImport } from './routes/_dashboard/dashboard/settings/billing'
import { Route as DashboardDashboardSettingsApiKeysRouteImport } from './routes/_dashboard/dashboard/settings/api-keys'
import { Route as DashboardDashboardAgentsNewRouteImport } from './routes/_dashboard/dashboard/agents/new'
import { Route as DashboardDashboardAgentsIdIndexRouteImport } from './routes/_dashboard/dashboard/agents/$id/index'
import { Route as DashboardDashboardAgentsIdWebhooksRouteImport } from './routes/_dashboard/dashboard/agents/$id/webhooks'
import { Route as DashboardDashboardAgentsIdPlaygroundRouteImport } from './routes/_dashboard/dashboard/agents/$id/playground'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardUsageIndexRoute =
  DashboardDashboardUsageIndexRouteImport.update({
    id: '/dashboard/usage/',
    path: '/dashboard/usage/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardToolsIndexRoute =
  DashboardDashboardToolsIndexRouteImport.update({
    id: '/dashboard/tools/',
    path: '/dashboard/tools/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsIndexRoute =
  DashboardDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAnalyticsIndexRoute =
  DashboardDashboardAnalyticsIndexRouteImport.update({
    id: '/dashboard/analytics/',
    path: '/dashboard/analytics/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsIndexRoute =
  DashboardDashboardAgentsIndexRouteImport.update({
    id: '/dashboard/agents/',
    path: '/dashboard/agents/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardToolsNewRoute =
  DashboardDashboardToolsNewRouteImport.update({
    id: '/dashboard/tools/new',
    path: '/dashboard/tools/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsTeamRoute =
  DashboardDashboardSettingsTeamRouteImport.update({
    id: '/dashboard/settings/team',
    path: '/dashboard/settings/team',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsBillingRoute =
  DashboardDashboardSettingsBillingRouteImport.update({
    id: '/dashboard/settings/billing',
    path: '/dashboard/settings/billing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsApiKeysRoute =
  DashboardDashboardSettingsApiKeysRouteImport.update({
    id: '/dashboard/settings/api-keys',
    path: '/dashboard/settings/api-keys',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsNewRoute =
  DashboardDashboardAgentsNewRouteImport.update({
    id: '/dashboard/agents/new',
    path: '/dashboard/agents/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsIdIndexRoute =
  DashboardDashboardAgentsIdIndexRouteImport.update({
    id: '/dashboard/agents/$id/',
    path: '/dashboard/agents/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsIdWebhooksRoute =
  DashboardDashboardAgentsIdWebhooksRouteImport.update({
    id: '/dashboard/agents/$id/webhooks',
    path: '/dashboard/agents/$id/webhooks',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsIdPlaygroundRoute =
  DashboardDashboardAgentsIdPlaygroundRouteImport.update({
    id: '/dashboard/agents/$id/playground',
    path: '/dashboard/agents/$id/playground',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/new': typeof AgentsNewRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/agents/new': typeof DashboardDashboardAgentsNewRoute
  '/dashboard/settings/api-keys': typeof DashboardDashboardSettingsApiKeysRoute
  '/dashboard/settings/billing': typeof DashboardDashboardSettingsBillingRoute
  '/dashboard/settings/team': typeof DashboardDashboardSettingsTeamRoute
  '/dashboard/tools/new': typeof DashboardDashboardToolsNewRoute
  '/dashboard/agents': typeof DashboardDashboardAgentsIndexRoute
  '/dashboard/analytics': typeof DashboardDashboardAnalyticsIndexRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
  '/dashboard/tools': typeof DashboardDashboardToolsIndexRoute
  '/dashboard/usage': typeof DashboardDashboardUsageIndexRoute
  '/dashboard/agents/$id/playground': typeof DashboardDashboardAgentsIdPlaygroundRoute
  '/dashboard/agents/$id/webhooks': typeof DashboardDashboardAgentsIdWebhooksRoute
  '/dashboard/agents/$id': typeof DashboardDashboardAgentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/new': typeof AgentsNewRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/agents/new': typeof DashboardDashboardAgentsNewRoute
  '/dashboard/settings/api-keys': typeof DashboardDashboardSettingsApiKeysRoute
  '/dashboard/settings/billing': typeof DashboardDashboardSettingsBillingRoute
  '/dashboard/settings/team': typeof DashboardDashboardSettingsTeamRoute
  '/dashboard/tools/new': typeof DashboardDashboardToolsNewRoute
  '/dashboard/agents': typeof DashboardDashboardAgentsIndexRoute
  '/dashboard/analytics': typeof DashboardDashboardAnalyticsIndexRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
  '/dashboard/tools': typeof DashboardDashboardToolsIndexRoute
  '/dashboard/usage': typeof DashboardDashboardUsageIndexRoute
  '/dashboard/agents/$id/playground': typeof DashboardDashboardAgentsIdPlaygroundRoute
  '/dashboard/agents/$id/webhooks': typeof DashboardDashboardAgentsIdWebhooksRoute
  '/dashboard/agents/$id': typeof DashboardDashboardAgentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/agents/new': typeof DashboardDashboardAgentsNewRoute
  '/_dashboard/dashboard/settings/api-keys': typeof DashboardDashboardSettingsApiKeysRoute
  '/_dashboard/dashboard/settings/billing': typeof DashboardDashboardSettingsBillingRoute
  '/_dashboard/dashboard/settings/team': typeof DashboardDashboardSettingsTeamRoute
  '/_dashboard/dashboard/tools/new': typeof DashboardDashboardToolsNewRoute
  '/_dashboard/dashboard/agents/': typeof DashboardDashboardAgentsIndexRoute
  '/_dashboard/dashboard/analytics/': typeof DashboardDashboardAnalyticsIndexRoute
  '/_dashboard/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
  '/_dashboard/dashboard/tools/': typeof DashboardDashboardToolsIndexRoute
  '/_dashboard/dashboard/usage/': typeof DashboardDashboardUsageIndexRoute
  '/_dashboard/dashboard/agents/$id/playground': typeof DashboardDashboardAgentsIdPlaygroundRoute
  '/_dashboard/dashboard/agents/$id/webhooks': typeof DashboardDashboardAgentsIdWebhooksRoute
  '/_dashboard/dashboard/agents/$id/': typeof DashboardDashboardAgentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/new'
    | '/dashboard'
    | '/dashboard/agents/new'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/team'
    | '/dashboard/tools/new'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/dashboard/tools'
    | '/dashboard/usage'
    | '/dashboard/agents/$id/playground'
    | '/dashboard/agents/$id/webhooks'
    | '/dashboard/agents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/new'
    | '/dashboard'
    | '/dashboard/agents/new'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/team'
    | '/dashboard/tools/new'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/dashboard/tools'
    | '/dashboard/usage'
    | '/dashboard/agents/$id/playground'
    | '/dashboard/agents/$id/webhooks'
    | '/dashboard/agents/$id'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/agents/new'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/agents/new'
    | '/_dashboard/dashboard/settings/api-keys'
    | '/_dashboard/dashboard/settings/billing'
    | '/_dashboard/dashboard/settings/team'
    | '/_dashboard/dashboard/tools/new'
    | '/_dashboard/dashboard/agents/'
    | '/_dashboard/dashboard/analytics/'
    | '/_dashboard/dashboard/settings/'
    | '/_dashboard/dashboard/tools/'
    | '/_dashboard/dashboard/usage/'
    | '/_dashboard/dashboard/agents/$id/playground'
    | '/_dashboard/dashboard/agents/$id/webhooks'
    | '/_dashboard/dashboard/agents/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AgentsNewRoute: typeof AgentsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/usage/': {
      id: '/_dashboard/dashboard/usage/'
      path: '/dashboard/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardDashboardUsageIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/tools/': {
      id: '/_dashboard/dashboard/tools/'
      path: '/dashboard/tools'
      fullPath: '/dashboard/tools'
      preLoaderRoute: typeof DashboardDashboardToolsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/': {
      id: '/_dashboard/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/analytics/': {
      id: '/_dashboard/dashboard/analytics/'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardDashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/': {
      id: '/_dashboard/dashboard/agents/'
      path: '/dashboard/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardDashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/tools/new': {
      id: '/_dashboard/dashboard/tools/new'
      path: '/dashboard/tools/new'
      fullPath: '/dashboard/tools/new'
      preLoaderRoute: typeof DashboardDashboardToolsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/team': {
      id: '/_dashboard/dashboard/settings/team'
      path: '/dashboard/settings/team'
      fullPath: '/dashboard/settings/team'
      preLoaderRoute: typeof DashboardDashboardSettingsTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/billing': {
      id: '/_dashboard/dashboard/settings/billing'
      path: '/dashboard/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardDashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/api-keys': {
      id: '/_dashboard/dashboard/settings/api-keys'
      path: '/dashboard/settings/api-keys'
      fullPath: '/dashboard/settings/api-keys'
      preLoaderRoute: typeof DashboardDashboardSettingsApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/new': {
      id: '/_dashboard/dashboard/agents/new'
      path: '/dashboard/agents/new'
      fullPath: '/dashboard/agents/new'
      preLoaderRoute: typeof DashboardDashboardAgentsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/$id/': {
      id: '/_dashboard/dashboard/agents/$id/'
      path: '/dashboard/agents/$id'
      fullPath: '/dashboard/agents/$id'
      preLoaderRoute: typeof DashboardDashboardAgentsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/$id/webhooks': {
      id: '/_dashboard/dashboard/agents/$id/webhooks'
      path: '/dashboard/agents/$id/webhooks'
      fullPath: '/dashboard/agents/$id/webhooks'
      preLoaderRoute: typeof DashboardDashboardAgentsIdWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/$id/playground': {
      id: '/_dashboard/dashboard/agents/$id/playground'
      path: '/dashboard/agents/$id/playground'
      fullPath: '/dashboard/agents/$id/playground'
      preLoaderRoute: typeof DashboardDashboardAgentsIdPlaygroundRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardAgentsNewRoute: typeof DashboardDashboardAgentsNewRoute
  DashboardDashboardSettingsApiKeysRoute: typeof DashboardDashboardSettingsApiKeysRoute
  DashboardDashboardSettingsBillingRoute: typeof DashboardDashboardSettingsBillingRoute
  DashboardDashboardSettingsTeamRoute: typeof DashboardDashboardSettingsTeamRoute
  DashboardDashboardToolsNewRoute: typeof DashboardDashboardToolsNewRoute
  DashboardDashboardAgentsIndexRoute: typeof DashboardDashboardAgentsIndexRoute
  DashboardDashboardAnalyticsIndexRoute: typeof DashboardDashboardAnalyticsIndexRoute
  DashboardDashboardSettingsIndexRoute: typeof DashboardDashboardSettingsIndexRoute
  DashboardDashboardToolsIndexRoute: typeof DashboardDashboardToolsIndexRoute
  DashboardDashboardUsageIndexRoute: typeof DashboardDashboardUsageIndexRoute
  DashboardDashboardAgentsIdPlaygroundRoute: typeof DashboardDashboardAgentsIdPlaygroundRoute
  DashboardDashboardAgentsIdWebhooksRoute: typeof DashboardDashboardAgentsIdWebhooksRoute
  DashboardDashboardAgentsIdIndexRoute: typeof DashboardDashboardAgentsIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardAgentsNewRoute: DashboardDashboardAgentsNewRoute,
  DashboardDashboardSettingsApiKeysRoute:
    DashboardDashboardSettingsApiKeysRoute,
  DashboardDashboardSettingsBillingRoute:
    DashboardDashboardSettingsBillingRoute,
  DashboardDashboardSettingsTeamRoute: DashboardDashboardSettingsTeamRoute,
  DashboardDashboardToolsNewRoute: DashboardDashboardToolsNewRoute,
  DashboardDashboardAgentsIndexRoute: DashboardDashboardAgentsIndexRoute,
  DashboardDashboardAnalyticsIndexRoute: DashboardDashboardAnalyticsIndexRoute,
  DashboardDashboardSettingsIndexRoute: DashboardDashboardSettingsIndexRoute,
  DashboardDashboardToolsIndexRoute: DashboardDashboardToolsIndexRoute,
  DashboardDashboardUsageIndexRoute: DashboardDashboardUsageIndexRoute,
  DashboardDashboardAgentsIdPlaygroundRoute:
    DashboardDashboardAgentsIdPlaygroundRoute,
  DashboardDashboardAgentsIdWebhooksRoute:
    DashboardDashboardAgentsIdWebhooksRoute,
  DashboardDashboardAgentsIdIndexRoute: DashboardDashboardAgentsIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AgentsNewRoute: AgentsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
