/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ToolsRouteImport } from './routes/tools'

const ToolsRoute = ToolsRouteImport.update({
	id: '/tools',
	path: '/tools',
	getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
	id: '/settings',
	path: '/settings',
	getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
	id: '/agents',
	path: '/agents',
	getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
	id: '/',
	path: '/',
	getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
	'/': typeof IndexRoute
	'/agents': typeof AgentsRoute
	'/settings': typeof SettingsRoute
	'/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
	'/': typeof IndexRoute
	'/agents': typeof AgentsRoute
	'/settings': typeof SettingsRoute
	'/tools': typeof ToolsRoute
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport
	'/': typeof IndexRoute
	'/agents': typeof AgentsRoute
	'/settings': typeof SettingsRoute
	'/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths: '/' | '/agents' | '/settings' | '/tools'
	fileRoutesByTo: FileRoutesByTo
	to: '/' | '/agents' | '/settings' | '/tools'
	id: '__root__' | '/' | '/agents' | '/settings' | '/tools'
	fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute
	AgentsRoute: typeof AgentsRoute
	SettingsRoute: typeof SettingsRoute
	ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/tools': {
			id: '/tools'
			path: '/tools'
			fullPath: '/tools'
			preLoaderRoute: typeof ToolsRouteImport
			parentRoute: typeof rootRouteImport
		}
		'/settings': {
			id: '/settings'
			path: '/settings'
			fullPath: '/settings'
			preLoaderRoute: typeof SettingsRouteImport
			parentRoute: typeof rootRouteImport
		}
		'/agents': {
			id: '/agents'
			path: '/agents'
			fullPath: '/agents'
			preLoaderRoute: typeof AgentsRouteImport
			parentRoute: typeof rootRouteImport
		}
		'/': {
			id: '/'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof IndexRouteImport
			parentRoute: typeof rootRouteImport
		}
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	AgentsRoute: AgentsRoute,
	SettingsRoute: SettingsRoute,
	ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>()
