/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as EmbedAgentIdRouteImport } from './routes/embed/$agentId'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardUsageIndexRouteImport } from './routes/_dashboard/dashboard/usage/index'
import { Route as DashboardDashboardToolsIndexRouteImport } from './routes/_dashboard/dashboard/tools/index'
import { Route as DashboardDashboardSettingsIndexRouteImport } from './routes/_dashboard/dashboard/settings/index'
import { Route as DashboardDashboardAnalyticsIndexRouteImport } from './routes/_dashboard/dashboard/analytics/index'
import { Route as DashboardDashboardAgentsIndexRouteImport } from './routes/_dashboard/dashboard/agents/index'
import { Route as DashboardDashboardToolsNewRouteImport } from './routes/_dashboard/dashboard/tools/new'
import { Route as DashboardDashboardToolsIdRouteImport } from './routes/_dashboard/dashboard/tools/$id'
import { Route as DashboardDashboardSettingsTeamRouteImport } from './routes/_dashboard/dashboard/settings/team'
import { Route as DashboardDashboardSettingsBillingRouteImport } from './routes/_dashboard/dashboard/settings/billing'
import { Route as DashboardDashboardSettingsAuditLogsRouteImport } from './routes/_dashboard/dashboard/settings/audit-logs'
import { Route as DashboardDashboardSettingsApiKeysRouteImport } from './routes/_dashboard/dashboard/settings/api-keys'
import { Route as DashboardDashboardAgentsTemplatesRouteImport } from './routes/_dashboard/dashboard/agents/templates'
import { Route as DashboardDashboardAgentsNewRouteImport } from './routes/_dashboard/dashboard/agents/new'
import { Route as DashboardDashboardAgentsIdIndexRouteImport } from './routes/_dashboard/dashboard/agents/$id/index'
import { Route as DashboardDashboardAgentsIdWebhooksRouteImport } from './routes/_dashboard/dashboard/agents/$id/webhooks'
import { Route as DashboardDashboardAgentsIdPlaygroundRouteImport } from './routes/_dashboard/dashboard/agents/$id/playground'
import { Route as DashboardDashboardAgentsIdEmbedRouteImport } from './routes/_dashboard/dashboard/agents/$id/embed'
import { Route as DashboardDashboardAgentsIdConversationsRouteImport } from './routes/_dashboard/dashboard/agents/$id/conversations'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const EmbedAgentIdRoute = EmbedAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => EmbedRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardUsageIndexRoute =
  DashboardDashboardUsageIndexRouteImport.update({
    id: '/dashboard/usage/',
    path: '/dashboard/usage/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardToolsIndexRoute =
  DashboardDashboardToolsIndexRouteImport.update({
    id: '/dashboard/tools/',
    path: '/dashboard/tools/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsIndexRoute =
  DashboardDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAnalyticsIndexRoute =
  DashboardDashboardAnalyticsIndexRouteImport.update({
    id: '/dashboard/analytics/',
    path: '/dashboard/analytics/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsIndexRoute =
  DashboardDashboardAgentsIndexRouteImport.update({
    id: '/dashboard/agents/',
    path: '/dashboard/agents/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardToolsNewRoute =
  DashboardDashboardToolsNewRouteImport.update({
    id: '/dashboard/tools/new',
    path: '/dashboard/tools/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardToolsIdRoute =
  DashboardDashboardToolsIdRouteImport.update({
    id: '/dashboard/tools/$id',
    path: '/dashboard/tools/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsTeamRoute =
  DashboardDashboardSettingsTeamRouteImport.update({
    id: '/dashboard/settings/team',
    path: '/dashboard/settings/team',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsBillingRoute =
  DashboardDashboardSettingsBillingRouteImport.update({
    id: '/dashboard/settings/billing',
    path: '/dashboard/settings/billing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsAuditLogsRoute =
  DashboardDashboardSettingsAuditLogsRouteImport.update({
    id: '/dashboard/settings/audit-logs',
    path: '/dashboard/settings/audit-logs',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsApiKeysRoute =
  DashboardDashboardSettingsApiKeysRouteImport.update({
    id: '/dashboard/settings/api-keys',
    path: '/dashboard/settings/api-keys',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsTemplatesRoute =
  DashboardDashboardAgentsTemplatesRouteImport.update({
    id: '/dashboard/agents/templates',
    path: '/dashboard/agents/templates',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsNewRoute =
  DashboardDashboardAgentsNewRouteImport.update({
    id: '/dashboard/agents/new',
    path: '/dashboard/agents/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsIdIndexRoute =
  DashboardDashboardAgentsIdIndexRouteImport.update({
    id: '/dashboard/agents/$id/',
    path: '/dashboard/agents/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsIdWebhooksRoute =
  DashboardDashboardAgentsIdWebhooksRouteImport.update({
    id: '/dashboard/agents/$id/webhooks',
    path: '/dashboard/agents/$id/webhooks',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsIdPlaygroundRoute =
  DashboardDashboardAgentsIdPlaygroundRouteImport.update({
    id: '/dashboard/agents/$id/playground',
    path: '/dashboard/agents/$id/playground',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsIdEmbedRoute =
  DashboardDashboardAgentsIdEmbedRouteImport.update({
    id: '/dashboard/agents/$id/embed',
    path: '/dashboard/agents/$id/embed',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardAgentsIdConversationsRoute =
  DashboardDashboardAgentsIdConversationsRouteImport.update({
    id: '/dashboard/agents/$id/conversations',
    path: '/dashboard/agents/$id/conversations',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/embed': typeof EmbedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/docs/$': typeof DocsSplatRoute
  '/embed/$agentId': typeof EmbedAgentIdRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/agents/new': typeof DashboardDashboardAgentsNewRoute
  '/dashboard/agents/templates': typeof DashboardDashboardAgentsTemplatesRoute
  '/dashboard/settings/api-keys': typeof DashboardDashboardSettingsApiKeysRoute
  '/dashboard/settings/audit-logs': typeof DashboardDashboardSettingsAuditLogsRoute
  '/dashboard/settings/billing': typeof DashboardDashboardSettingsBillingRoute
  '/dashboard/settings/team': typeof DashboardDashboardSettingsTeamRoute
  '/dashboard/tools/$id': typeof DashboardDashboardToolsIdRoute
  '/dashboard/tools/new': typeof DashboardDashboardToolsNewRoute
  '/dashboard/agents': typeof DashboardDashboardAgentsIndexRoute
  '/dashboard/analytics': typeof DashboardDashboardAnalyticsIndexRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
  '/dashboard/tools': typeof DashboardDashboardToolsIndexRoute
  '/dashboard/usage': typeof DashboardDashboardUsageIndexRoute
  '/dashboard/agents/$id/conversations': typeof DashboardDashboardAgentsIdConversationsRoute
  '/dashboard/agents/$id/embed': typeof DashboardDashboardAgentsIdEmbedRoute
  '/dashboard/agents/$id/playground': typeof DashboardDashboardAgentsIdPlaygroundRoute
  '/dashboard/agents/$id/webhooks': typeof DashboardDashboardAgentsIdWebhooksRoute
  '/dashboard/agents/$id': typeof DashboardDashboardAgentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/docs/$': typeof DocsSplatRoute
  '/embed/$agentId': typeof EmbedAgentIdRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/agents/new': typeof DashboardDashboardAgentsNewRoute
  '/dashboard/agents/templates': typeof DashboardDashboardAgentsTemplatesRoute
  '/dashboard/settings/api-keys': typeof DashboardDashboardSettingsApiKeysRoute
  '/dashboard/settings/audit-logs': typeof DashboardDashboardSettingsAuditLogsRoute
  '/dashboard/settings/billing': typeof DashboardDashboardSettingsBillingRoute
  '/dashboard/settings/team': typeof DashboardDashboardSettingsTeamRoute
  '/dashboard/tools/$id': typeof DashboardDashboardToolsIdRoute
  '/dashboard/tools/new': typeof DashboardDashboardToolsNewRoute
  '/dashboard/agents': typeof DashboardDashboardAgentsIndexRoute
  '/dashboard/analytics': typeof DashboardDashboardAnalyticsIndexRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
  '/dashboard/tools': typeof DashboardDashboardToolsIndexRoute
  '/dashboard/usage': typeof DashboardDashboardUsageIndexRoute
  '/dashboard/agents/$id/conversations': typeof DashboardDashboardAgentsIdConversationsRoute
  '/dashboard/agents/$id/embed': typeof DashboardDashboardAgentsIdEmbedRoute
  '/dashboard/agents/$id/playground': typeof DashboardDashboardAgentsIdPlaygroundRoute
  '/dashboard/agents/$id/webhooks': typeof DashboardDashboardAgentsIdWebhooksRoute
  '/dashboard/agents/$id': typeof DashboardDashboardAgentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/embed': typeof EmbedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/docs/$': typeof DocsSplatRoute
  '/embed/$agentId': typeof EmbedAgentIdRoute
  '/docs/': typeof DocsIndexRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/agents/new': typeof DashboardDashboardAgentsNewRoute
  '/_dashboard/dashboard/agents/templates': typeof DashboardDashboardAgentsTemplatesRoute
  '/_dashboard/dashboard/settings/api-keys': typeof DashboardDashboardSettingsApiKeysRoute
  '/_dashboard/dashboard/settings/audit-logs': typeof DashboardDashboardSettingsAuditLogsRoute
  '/_dashboard/dashboard/settings/billing': typeof DashboardDashboardSettingsBillingRoute
  '/_dashboard/dashboard/settings/team': typeof DashboardDashboardSettingsTeamRoute
  '/_dashboard/dashboard/tools/$id': typeof DashboardDashboardToolsIdRoute
  '/_dashboard/dashboard/tools/new': typeof DashboardDashboardToolsNewRoute
  '/_dashboard/dashboard/agents/': typeof DashboardDashboardAgentsIndexRoute
  '/_dashboard/dashboard/analytics/': typeof DashboardDashboardAnalyticsIndexRoute
  '/_dashboard/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
  '/_dashboard/dashboard/tools/': typeof DashboardDashboardToolsIndexRoute
  '/_dashboard/dashboard/usage/': typeof DashboardDashboardUsageIndexRoute
  '/_dashboard/dashboard/agents/$id/conversations': typeof DashboardDashboardAgentsIdConversationsRoute
  '/_dashboard/dashboard/agents/$id/embed': typeof DashboardDashboardAgentsIdEmbedRoute
  '/_dashboard/dashboard/agents/$id/playground': typeof DashboardDashboardAgentsIdPlaygroundRoute
  '/_dashboard/dashboard/agents/$id/webhooks': typeof DashboardDashboardAgentsIdWebhooksRoute
  '/_dashboard/dashboard/agents/$id/': typeof DashboardDashboardAgentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/embed'
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/docs/$'
    | '/embed/$agentId'
    | '/docs/'
    | '/dashboard'
    | '/dashboard/agents/new'
    | '/dashboard/agents/templates'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/team'
    | '/dashboard/tools/$id'
    | '/dashboard/tools/new'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/dashboard/tools'
    | '/dashboard/usage'
    | '/dashboard/agents/$id/conversations'
    | '/dashboard/agents/$id/embed'
    | '/dashboard/agents/$id/playground'
    | '/dashboard/agents/$id/webhooks'
    | '/dashboard/agents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embed'
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/docs/$'
    | '/embed/$agentId'
    | '/docs'
    | '/dashboard'
    | '/dashboard/agents/new'
    | '/dashboard/agents/templates'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/team'
    | '/dashboard/tools/$id'
    | '/dashboard/tools/new'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/dashboard/tools'
    | '/dashboard/usage'
    | '/dashboard/agents/$id/conversations'
    | '/dashboard/agents/$id/embed'
    | '/dashboard/agents/$id/playground'
    | '/dashboard/agents/$id/webhooks'
    | '/dashboard/agents/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/docs'
    | '/embed'
    | '/privacy'
    | '/terms'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/docs/$'
    | '/embed/$agentId'
    | '/docs/'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/agents/new'
    | '/_dashboard/dashboard/agents/templates'
    | '/_dashboard/dashboard/settings/api-keys'
    | '/_dashboard/dashboard/settings/audit-logs'
    | '/_dashboard/dashboard/settings/billing'
    | '/_dashboard/dashboard/settings/team'
    | '/_dashboard/dashboard/tools/$id'
    | '/_dashboard/dashboard/tools/new'
    | '/_dashboard/dashboard/agents/'
    | '/_dashboard/dashboard/analytics/'
    | '/_dashboard/dashboard/settings/'
    | '/_dashboard/dashboard/tools/'
    | '/_dashboard/dashboard/usage/'
    | '/_dashboard/dashboard/agents/$id/conversations'
    | '/_dashboard/dashboard/agents/$id/embed'
    | '/_dashboard/dashboard/agents/$id/playground'
    | '/_dashboard/dashboard/agents/$id/webhooks'
    | '/_dashboard/dashboard/agents/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  EmbedRoute: typeof EmbedRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/embed/$agentId': {
      id: '/embed/$agentId'
      path: '/$agentId'
      fullPath: '/embed/$agentId'
      preLoaderRoute: typeof EmbedAgentIdRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/usage/': {
      id: '/_dashboard/dashboard/usage/'
      path: '/dashboard/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardDashboardUsageIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/tools/': {
      id: '/_dashboard/dashboard/tools/'
      path: '/dashboard/tools'
      fullPath: '/dashboard/tools'
      preLoaderRoute: typeof DashboardDashboardToolsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/': {
      id: '/_dashboard/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/analytics/': {
      id: '/_dashboard/dashboard/analytics/'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardDashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/': {
      id: '/_dashboard/dashboard/agents/'
      path: '/dashboard/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardDashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/tools/new': {
      id: '/_dashboard/dashboard/tools/new'
      path: '/dashboard/tools/new'
      fullPath: '/dashboard/tools/new'
      preLoaderRoute: typeof DashboardDashboardToolsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/tools/$id': {
      id: '/_dashboard/dashboard/tools/$id'
      path: '/dashboard/tools/$id'
      fullPath: '/dashboard/tools/$id'
      preLoaderRoute: typeof DashboardDashboardToolsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/team': {
      id: '/_dashboard/dashboard/settings/team'
      path: '/dashboard/settings/team'
      fullPath: '/dashboard/settings/team'
      preLoaderRoute: typeof DashboardDashboardSettingsTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/billing': {
      id: '/_dashboard/dashboard/settings/billing'
      path: '/dashboard/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardDashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/audit-logs': {
      id: '/_dashboard/dashboard/settings/audit-logs'
      path: '/dashboard/settings/audit-logs'
      fullPath: '/dashboard/settings/audit-logs'
      preLoaderRoute: typeof DashboardDashboardSettingsAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings/api-keys': {
      id: '/_dashboard/dashboard/settings/api-keys'
      path: '/dashboard/settings/api-keys'
      fullPath: '/dashboard/settings/api-keys'
      preLoaderRoute: typeof DashboardDashboardSettingsApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/templates': {
      id: '/_dashboard/dashboard/agents/templates'
      path: '/dashboard/agents/templates'
      fullPath: '/dashboard/agents/templates'
      preLoaderRoute: typeof DashboardDashboardAgentsTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/new': {
      id: '/_dashboard/dashboard/agents/new'
      path: '/dashboard/agents/new'
      fullPath: '/dashboard/agents/new'
      preLoaderRoute: typeof DashboardDashboardAgentsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/$id/': {
      id: '/_dashboard/dashboard/agents/$id/'
      path: '/dashboard/agents/$id'
      fullPath: '/dashboard/agents/$id'
      preLoaderRoute: typeof DashboardDashboardAgentsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/$id/webhooks': {
      id: '/_dashboard/dashboard/agents/$id/webhooks'
      path: '/dashboard/agents/$id/webhooks'
      fullPath: '/dashboard/agents/$id/webhooks'
      preLoaderRoute: typeof DashboardDashboardAgentsIdWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/$id/playground': {
      id: '/_dashboard/dashboard/agents/$id/playground'
      path: '/dashboard/agents/$id/playground'
      fullPath: '/dashboard/agents/$id/playground'
      preLoaderRoute: typeof DashboardDashboardAgentsIdPlaygroundRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/$id/embed': {
      id: '/_dashboard/dashboard/agents/$id/embed'
      path: '/dashboard/agents/$id/embed'
      fullPath: '/dashboard/agents/$id/embed'
      preLoaderRoute: typeof DashboardDashboardAgentsIdEmbedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/agents/$id/conversations': {
      id: '/_dashboard/dashboard/agents/$id/conversations'
      path: '/dashboard/agents/$id/conversations'
      fullPath: '/dashboard/agents/$id/conversations'
      preLoaderRoute: typeof DashboardDashboardAgentsIdConversationsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardAgentsNewRoute: typeof DashboardDashboardAgentsNewRoute
  DashboardDashboardAgentsTemplatesRoute: typeof DashboardDashboardAgentsTemplatesRoute
  DashboardDashboardSettingsApiKeysRoute: typeof DashboardDashboardSettingsApiKeysRoute
  DashboardDashboardSettingsAuditLogsRoute: typeof DashboardDashboardSettingsAuditLogsRoute
  DashboardDashboardSettingsBillingRoute: typeof DashboardDashboardSettingsBillingRoute
  DashboardDashboardSettingsTeamRoute: typeof DashboardDashboardSettingsTeamRoute
  DashboardDashboardToolsIdRoute: typeof DashboardDashboardToolsIdRoute
  DashboardDashboardToolsNewRoute: typeof DashboardDashboardToolsNewRoute
  DashboardDashboardAgentsIndexRoute: typeof DashboardDashboardAgentsIndexRoute
  DashboardDashboardAnalyticsIndexRoute: typeof DashboardDashboardAnalyticsIndexRoute
  DashboardDashboardSettingsIndexRoute: typeof DashboardDashboardSettingsIndexRoute
  DashboardDashboardToolsIndexRoute: typeof DashboardDashboardToolsIndexRoute
  DashboardDashboardUsageIndexRoute: typeof DashboardDashboardUsageIndexRoute
  DashboardDashboardAgentsIdConversationsRoute: typeof DashboardDashboardAgentsIdConversationsRoute
  DashboardDashboardAgentsIdEmbedRoute: typeof DashboardDashboardAgentsIdEmbedRoute
  DashboardDashboardAgentsIdPlaygroundRoute: typeof DashboardDashboardAgentsIdPlaygroundRoute
  DashboardDashboardAgentsIdWebhooksRoute: typeof DashboardDashboardAgentsIdWebhooksRoute
  DashboardDashboardAgentsIdIndexRoute: typeof DashboardDashboardAgentsIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardAgentsNewRoute: DashboardDashboardAgentsNewRoute,
  DashboardDashboardAgentsTemplatesRoute:
    DashboardDashboardAgentsTemplatesRoute,
  DashboardDashboardSettingsApiKeysRoute:
    DashboardDashboardSettingsApiKeysRoute,
  DashboardDashboardSettingsAuditLogsRoute:
    DashboardDashboardSettingsAuditLogsRoute,
  DashboardDashboardSettingsBillingRoute:
    DashboardDashboardSettingsBillingRoute,
  DashboardDashboardSettingsTeamRoute: DashboardDashboardSettingsTeamRoute,
  DashboardDashboardToolsIdRoute: DashboardDashboardToolsIdRoute,
  DashboardDashboardToolsNewRoute: DashboardDashboardToolsNewRoute,
  DashboardDashboardAgentsIndexRoute: DashboardDashboardAgentsIndexRoute,
  DashboardDashboardAnalyticsIndexRoute: DashboardDashboardAnalyticsIndexRoute,
  DashboardDashboardSettingsIndexRoute: DashboardDashboardSettingsIndexRoute,
  DashboardDashboardToolsIndexRoute: DashboardDashboardToolsIndexRoute,
  DashboardDashboardUsageIndexRoute: DashboardDashboardUsageIndexRoute,
  DashboardDashboardAgentsIdConversationsRoute:
    DashboardDashboardAgentsIdConversationsRoute,
  DashboardDashboardAgentsIdEmbedRoute: DashboardDashboardAgentsIdEmbedRoute,
  DashboardDashboardAgentsIdPlaygroundRoute:
    DashboardDashboardAgentsIdPlaygroundRoute,
  DashboardDashboardAgentsIdWebhooksRoute:
    DashboardDashboardAgentsIdWebhooksRoute,
  DashboardDashboardAgentsIdIndexRoute: DashboardDashboardAgentsIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface EmbedRouteChildren {
  EmbedAgentIdRoute: typeof EmbedAgentIdRoute
}

const EmbedRouteChildren: EmbedRouteChildren = {
  EmbedAgentIdRoute: EmbedAgentIdRoute,
}

const EmbedRouteWithChildren = EmbedRoute._addFileChildren(EmbedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  EmbedRoute: EmbedRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
