/**
 * Cloudflare Worker Entry Point
 *
 * This file exports the Durable Object classes required for CF Agents.
 * The main worker is generated by OpenNext, but we need to export
 * these classes for Durable Objects to work.
 */

// Export Durable Object classes
export { HareAgent } from './lib/agents/hare-agent'
export { HareMcpAgent } from './lib/agents/mcp-agent'
