"use client";

import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Send } from "lucide-react";

export default function PlaygroundPage({ params }: { params: { id: string } }) {
	const [messages, setMessages] = useState([
		{
			role: "assistant",
			content: "Hello! I'm your Customer Support Agent. How can I help you today?",
		},
	]);
	const [input, setInput] = useState("");

	const handleSend = () => {
		if (!input.trim()) return;

		setMessages([...messages, { role: "user", content: input }]);
		setInput("");

		setTimeout(() => {
			setMessages((prev) => [
				...prev,
				{
					role: "assistant",
					content: "This is a demo response. In production, this would be generated by your AI agent.",
				},
			]);
		}, 1000);
	};

	return (
		<div className="flex-1 space-y-4 p-8 pt-6 h-full">
			<div className="flex items-center justify-between">
				<div>
					<div className="flex items-center gap-3">
						<h2 className="text-3xl font-bold tracking-tight">Agent Playground</h2>
						<Badge className="bg-emerald-100 text-emerald-700 dark:bg-emerald-900 dark:text-emerald-300">
							Active
						</Badge>
					</div>
					<p className="text-muted-foreground mt-2">Test and interact with your agent in real-time</p>
				</div>
			</div>

			<div className="grid gap-4 md:grid-cols-4 h-[calc(100vh-220px)]">
				<Card className="md:col-span-3 flex flex-col">
					<CardHeader>
						<CardTitle>Chat</CardTitle>
						<CardDescription>Test your agent's responses</CardDescription>
					</CardHeader>
					<CardContent className="flex-1 flex flex-col">
						<div className="flex-1 overflow-y-auto space-y-4 mb-4">
							{messages.map((message, i) => (
								<div
									key={i}
									className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}
								>
									<div
										className={`max-w-[80%] rounded-lg px-4 py-2 ${
											message.role === "user"
												? "bg-primary text-primary-foreground"
												: "bg-muted text-muted-foreground"
										}`}
									>
										{message.content}
									</div>
								</div>
							))}
						</div>
						<div className="flex gap-2">
							<Input
								value={input}
								onChange={(e) => setInput(e.target.value)}
								placeholder="Type a message..."
								onKeyDown={(e) => {
									if (e.key === "Enter" && !e.shiftKey) {
										e.preventDefault();
										handleSend();
									}
								}}
							/>
							<Button onClick={handleSend} size="icon">
								<Send className="h-4 w-4" />
							</Button>
						</div>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle>Settings</CardTitle>
					</CardHeader>
					<CardContent className="space-y-4">
						<div>
							<div className="text-sm font-medium mb-2">Model</div>
							<div className="text-sm text-muted-foreground">Claude Opus 4.5</div>
						</div>
						<div>
							<div className="text-sm font-medium mb-2">Temperature</div>
							<div className="text-sm text-muted-foreground">0.7</div>
						</div>
						<div>
							<div className="text-sm font-medium mb-2">Max Tokens</div>
							<div className="text-sm text-muted-foreground">2048</div>
						</div>
					</CardContent>
				</Card>
			</div>
		</div>
	);
}
