import { test as baseTest, expect, type Page } from '@playwright/test'
import { test } from './fixtures'

baseTest.describe('Usage Page - Unauthenticated', () => {
	baseTest.beforeEach(async ({ page }: { page: Page }) => {
		await page.goto('/dashboard/usage')
		await page.waitForLoadState('networkidle')
	})

	baseTest('displays usage heading', async ({ page }: { page: Page }) => {
		await expect(page.getByRole('heading', { name: 'Usage' })).toBeVisible()
	})

	baseTest('displays stat cards', async ({ page }: { page: Page }) => {
		// Wait for stat cards to load
		await expect(page.getByText('Total API Calls')).toBeVisible()
		await expect(page.getByText('Total Tokens')).toBeVisible()
		await expect(page.getByText('Active Agents')).toBeVisible()
		await expect(page.getByText('Period')).toBeVisible()
	})

	baseTest('displays token breakdown card', async ({ page }: { page: Page }) => {
		await expect(page.getByText('Token Breakdown')).toBeVisible()
		await expect(page.getByText('Input vs output tokens this period')).toBeVisible()
	})

	baseTest('displays usage by agent card', async ({ page }: { page: Page }) => {
		await expect(page.getByText('Usage by Agent')).toBeVisible()
		await expect(page.getByText('Token usage per deployed agent')).toBeVisible()
	})

	baseTest('displays about usage tracking card', async ({ page }: { page: Page }) => {
		await expect(page.getByText('About Usage Tracking')).toBeVisible()
	})

	baseTest('page has no 404 error', async ({ page }: { page: Page }) => {
		await expect(page.locator('body')).not.toContainText('404')
	})
})

baseTest.describe('Usage Page - Stat Cards', () => {
	baseTest.beforeEach(async ({ page }: { page: Page }) => {
		await page.goto('/dashboard/usage')
		await page.waitForLoadState('networkidle')
		// Wait for stat cards to load
		await expect(page.getByText('Total API Calls')).toBeVisible()
	})

	baseTest('total api calls card shows billing period description', async ({
		page,
	}: { page: Page }) => {
		const apiCallsCard = page.locator('[class*="card"]').filter({ hasText: 'Total API Calls' })
		await expect(apiCallsCard.getByText('This billing period')).toBeVisible()
	})

	baseTest('active agents card shows total agents count', async ({ page }: { page: Page }) => {
		const agentsCard = page.locator('[class*="card"]').filter({ hasText: 'Active Agents' })
		await expect(agentsCard.getByText(/total agents/)).toBeVisible()
	})
})

baseTest.describe('Usage Page - Token Breakdown', () => {
	baseTest.beforeEach(async ({ page }: { page: Page }) => {
		await page.goto('/dashboard/usage')
		await page.waitForLoadState('networkidle')
		// Wait for token breakdown section to load
		await expect(page.getByText('Token Breakdown')).toBeVisible()
	})

	baseTest('shows input tokens section', async ({ page }: { page: Page }) => {
		await expect(page.getByText('Input Tokens')).toBeVisible()
		await expect(page.getByText('Tokens sent to the model')).toBeVisible()
	})

	baseTest('shows output tokens section', async ({ page }: { page: Page }) => {
		await expect(page.getByText('Output Tokens')).toBeVisible()
		await expect(page.getByText('Tokens generated by the model')).toBeVisible()
	})
})

baseTest.describe('Usage Page - Usage by Agent', () => {
	baseTest.beforeEach(async ({ page }: { page: Page }) => {
		await page.goto('/dashboard/usage')
		await page.waitForLoadState('networkidle')
		// Wait for usage by agent section to load
		await expect(page.getByText('Usage by Agent')).toBeVisible()
	})

	baseTest('shows empty state when no deployed agents', async ({ page }: { page: Page }) => {
		// Either shows agents or empty state
		const emptyState = page.getByText('No deployed agents yet')
		const agentsList = page.locator('.rounded-lg').filter({ hasText: 'tools' })

		const hasEmptyState = await emptyState.isVisible().catch(() => false)
		const hasAgents = (await agentsList.count()) > 0

		expect(hasEmptyState || hasAgents).toBeTruthy()
	})
})

baseTest.describe('Usage Page - About Section', () => {
	baseTest.beforeEach(async ({ page }: { page: Page }) => {
		await page.goto('/dashboard/usage')
		await page.waitForLoadState('networkidle')
	})

	baseTest('explains usage tracking', async ({ page }: { page: Page }) => {
		await expect(
			page.getByText(/Usage is tracked automatically for all API calls/),
		).toBeVisible()
	})

	baseTest('mentions Cloudflare Workers AI pricing', async ({ page }: { page: Page }) => {
		await expect(page.getByText(/Cloudflare Workers AI pricing/)).toBeVisible()
	})
})

test.describe('Usage Page - Authenticated User', () => {
	test('authenticated user sees usage page with data', async ({ authenticatedPage }) => {
		await authenticatedPage.goto('/dashboard/usage')
		await authenticatedPage.waitForLoadState('networkidle')

		await expect(authenticatedPage.getByRole('heading', { name: 'Usage' })).toBeVisible()
		await expect(authenticatedPage.getByText('Total API Calls')).toBeVisible()
	})

	test('authenticated user sees token breakdown', async ({ authenticatedPage }) => {
		await authenticatedPage.goto('/dashboard/usage')
		await authenticatedPage.waitForLoadState('networkidle')

		await expect(authenticatedPage.getByText('Token Breakdown')).toBeVisible()
		await expect(authenticatedPage.getByText('Input Tokens')).toBeVisible()
		await expect(authenticatedPage.getByText('Output Tokens')).toBeVisible()
	})

	test('authenticated user sees usage by agent section', async ({ authenticatedPage }) => {
		await authenticatedPage.goto('/dashboard/usage')
		await authenticatedPage.waitForLoadState('networkidle')

		await expect(authenticatedPage.getByText('Usage by Agent')).toBeVisible()
	})
})

baseTest.describe('Usage Page - Responsive Design', () => {
	baseTest('displays correctly on mobile', async ({ page }: { page: Page }) => {
		await page.setViewportSize({ width: 375, height: 667 })
		await page.goto('/dashboard/usage')
		await page.waitForLoadState('networkidle')

		await expect(page.getByRole('heading', { name: 'Usage' })).toBeVisible()
		// Stat cards should stack on mobile
		await expect(page.getByText('Total API Calls')).toBeVisible()
	})

	baseTest('displays correctly on tablet', async ({ page }: { page: Page }) => {
		await page.setViewportSize({ width: 768, height: 1024 })
		await page.goto('/dashboard/usage')
		await page.waitForLoadState('networkidle')

		await expect(page.getByRole('heading', { name: 'Usage' })).toBeVisible()
		// All sections should be visible
		await expect(page.getByText('Token Breakdown')).toBeVisible()
		await expect(page.getByText('Usage by Agent')).toBeVisible()
	})

	baseTest('displays correctly on desktop', async ({ page }: { page: Page }) => {
		await page.setViewportSize({ width: 1920, height: 1080 })
		await page.goto('/dashboard/usage')
		await page.waitForLoadState('networkidle')

		// All stat cards should be in a grid
		await expect(page.getByText('Total API Calls')).toBeVisible()
		await expect(page.getByText('Total Tokens')).toBeVisible()
		await expect(page.getByText('Active Agents')).toBeVisible()
		await expect(page.getByText('Period')).toBeVisible()
	})
})

baseTest.describe('Usage Page - Loading States', () => {
	baseTest('shows skeleton loaders while loading', async ({ page }: { page: Page }) => {
		// Navigate with slow network to see loading state
		await page.route('**/api/usage**', async (route) => {
			await new Promise((resolve) => window.setTimeout(resolve, 500))
			await route.continue()
		})

		await page.goto('/dashboard/usage')

		// Check for skeleton elements (they appear briefly during load)
		const skeletons = page.locator('[class*="skeleton"]')
		// Page should either have skeletons during load or content after load
		const pageContent = await page.content()
		expect(
			pageContent.includes('skeleton') ||
				pageContent.includes('Total API Calls') ||
				pageContent.includes('Usage'),
		).toBeTruthy()
	})
})

baseTest.describe('Usage Page - Accessibility', () => {
	baseTest.beforeEach(async ({ page }: { page: Page }) => {
		await page.goto('/dashboard/usage')
		await page.waitForLoadState('networkidle')
	})

	baseTest('has proper heading hierarchy', async ({ page }: { page: Page }) => {
		// Should have h2 as main heading
		const h2 = page.locator('h2').first()
		await expect(h2).toBeVisible()
		await expect(h2).toContainText('Usage')
	})

	baseTest('card content is accessible', async ({ page }: { page: Page }) => {
		// Cards should have readable content
		const cards = page.locator('[class*="card"]')
		const count = await cards.count()
		expect(count).toBeGreaterThan(0)
	})
})
