/**
 * Cloudflare environment bindings interface.
 *
 * SDK users should declare their own CloudflareEnv type that matches
 * their wrangler.toml bindings. This interface shows the expected shape.
 *
 * Note: This interface doesn't have an index signature so it can be
 * properly extended by specific CloudflareEnv types generated by wrangler.
 *
 * @example
 * ```ts
 * // In your worker project - your Env extends the base HareEnv
 * interface Env extends HareEnv {
 *   AI: Ai
 *   KV: KVNamespace
 *   R2: R2Bucket
 *   DB: D1Database
 *   VECTORIZE: VectorizeIndex
 *   // Your custom bindings
 *   MY_CUSTOM_KV: KVNamespace
 * }
 * ```
 */
export interface HareEnv {
	/** Workers AI binding - required for AI tools */
	AI?: Ai

	/** KV namespace - required for KV tools */
	KV?: KVNamespace

	/** R2 bucket - required for R2 tools */
	R2?: R2Bucket

	/** D1 database - required for SQL tools */
	DB?: D1Database

	/** Vectorize index - required for memory tools */
	VECTORIZE?: VectorizeIndex

	/** Browser Rendering binding - required for browser tools */
	BROWSER?: Fetcher
}
