#!/usr/bin/env bun

/**
 * 🐇 Environment Variable Shim Script for Monorepo
 *
 * This script generates environment files for different apps in the monorepo
 * from a single root .env.local file. It handles:
 * - ⚡ Vite apps: copies env vars (VITE_* prefix for client-side)
 * - ☁️ Cloudflare Workers: generates .dev.vars (excludes VITE_* vars)
 *
 * Based on: https://github.com/timothymiller/t4-app/blob/master/.github/scripts/env.ts
 * Adapted for Bun and Hare's Cloudflare-first architecture
 *
 * Usage:
 *   bun run scripts/env.ts
 *
 * Automatically runs via postinstall hook (skipped in CI).
 */

import { randomBytes } from 'node:crypto'
import fs from 'fs-extra'
import { join } from 'node:path'

const isCI = process.env.CI === "true";
if (isCI) {
  console.log("🏃 CI detected, skipping .env file generation");
  process.exit(0);
}

console.log("🐇 Generating environment files for monorepo...");

const autogeneratedComment =
  "# 🤖 This file is autogenerated. To make changes, modify the root level .env.local file and run bun install\n\n";
const sourceFileName = ".env.local";

// Read the source .env.local file
const rootDir = join(import.meta.dir, "..");
const envFilePath = join(rootDir, sourceFileName);

if (!fs.existsSync(envFilePath)) {
  console.log("⚠️  .env.local file does not exist at root level");
  console.log(
    "💡 Create one from .env.local.example: cp .env.local.example .env.local",
  );
  process.exit(0);
}

let envFileContent = fs.readFileSync(envFilePath, 'utf8')

// Auto-generate BETTER_AUTH_SECRET if it is empty or missing
const authSecretMatch = envFileContent.match(/^BETTER_AUTH_SECRET=(.*)$/m)
if (!authSecretMatch) {
  // Key is missing entirely — append it
  const generated = randomBytes(32).toString('hex')
  envFileContent = `${envFileContent.trimEnd()}\nBETTER_AUTH_SECRET=${generated}\n`
  fs.writeFileSync(envFilePath, envFileContent, 'utf8')
  console.log("🔑 Generated BETTER_AUTH_SECRET (was missing)")
} else if (!authSecretMatch[1].trim()) {
  // Key exists but value is empty
  const generated = randomBytes(32).toString('hex')
  envFileContent = envFileContent.replace(
    /^BETTER_AUTH_SECRET=.*$/m,
    `BETTER_AUTH_SECRET=${generated}`,
  )
  fs.writeFileSync(envFilePath, envFileContent, 'utf8')
  console.log("🔑 Generated BETTER_AUTH_SECRET (was empty)")
}

/**
 * ⚡ Generate Vite .env.local file
 * Copies all env vars as-is (VITE_* prefix exposes to client)
 */
const viteOutputPath = join(rootDir, "apps", "web", ".env.local");
fs.outputFileSync(viteOutputPath, `${autogeneratedComment}${envFileContent}`)
console.log("✅ Generated apps/web/.env.local");

/**
 * ☁️ Generate Cloudflare .dev.vars file
 * Cloudflare Workers uses .dev.vars for local development instead of .env
 * VITE_* variables are excluded as they're client-side only
 */
const wranglerOutputPath = join(rootDir, "apps", "web", ".dev.vars");
const wranglerFileContent = envFileContent
  .split("\n")
  .filter((line) => {
    // Skip empty lines and comments
    if (!line.trim() || line.trim().startsWith("#")) {
      return true;
    }
    // Exclude VITE_* prefixed variables (client-side only)
    if (line.startsWith("VITE_")) {
      return false;
    }
    return true;
  })
  .join("\n");

fs.outputFileSync(wranglerOutputPath, `${autogeneratedComment}${wranglerFileContent}`)
console.log("✅ Generated apps/web/.dev.vars");

console.log("🎉 Environment files generated successfully!");
