// TODO: Re-enable once fumadocs-mdx path.join bundling issue is fixed
// @ts-expect-error - Virtual module generated by fumadocs-mdx Vite plugin at build time
// import { docs } from 'fumadocs-mdx:collections/server'
// import { loader } from 'fumadocs-core/source'

// Temporary stub while fumadocs is disabled
export const source = {
	baseUrl: '/docs',
	getPage: () => null,
	pageTree: { name: 'docs', children: [] },
}
