// @ts-expect-error - Virtual module generated by fumadocs-mdx Vite plugin at build time
// The .source directory is auto-generated when running dev or build
import { docs } from 'fumadocs-mdx:collections/server'
import { loader } from 'fumadocs-core/source'

export const source = loader({
	baseUrl: '/docs',
	source: docs.toFumadocsSource(),
})
